### ISSUE TITLE
Errors with @types when running ng-xi18n

### ISSUE THREAD

**Issue by danielcrisp** [klaascuvelier/ng2-i18n#2]
Me again.

I just tried running `../node_modules/.bin/ng-xi18n` from inside the `src` directory and I got a lot of errors. Mostly they seem to be related to `@types/core-js`:

```shell
/Volumes/Projects/lab/ng2-i18n/src   master±  ../node_modules/.bin/ng-xi18n
Error: Error at /Volumes/Projects/lab/ng2-i18n/node_modules/typescript/lib/lib.es2015.core.d.ts:17:14: Duplicate identifier 'PropertyKey'.
Error at /Volumes/Projects/lab/ng2-i18n/node_modules/@types/core-js/index.d.ts:21:14: Duplicate identifier 'PropertyKey'.
Error at /Volumes/Projects/lab/ng2-i18n/node_modules/@types/core-js/index.d.ts:85:5: All declarations of 'name' must have identical modifiers.
Error at /Volumes/Projects/lab/ng2-i18n/node_modules/@types/core-js/index.d.ts:145:5: Subsequent variable declarations must have the same type.  Variable '[Symbol.unscopables]' must be of type '{ copyWithin: boolean; entries: boolean; fill: boolean; find: boolean; findIndex: boolean; keys: ...', but here has type 'any'.
Error at /Volumes/Projects/lab/ng2-i18n/node_modules/@types/core-js/index.d.ts:262:5: All declarations of 'flags' must have identical modifiers.
Error at /Volumes/Projects/lab/ng2-i18n/node_modules/@types/core-js/index.d.ts:276:5: All declarations of 'EPSILON' must have identical modifiers.
Error at /Volumes/Projects/lab/ng2-i18n/node_modules/@types/core-js/index.d.ts:311:5: All declarations of 'MAX_SAFE_INTEGER' must have identical modifiers.
Error at /Volumes/Projects/lab/ng2-i18n/node_modules/@types/core-js/index.d.ts:318:5: All declarations of 'MIN_SAFE_INTEGER' must have identical modifiers.
Error at /Volumes/Projects/lab/ng2-i18n/node_modules/@types/core-js/index.d.ts:457:5: Subsequent variable declarations must have the same type.  Variable '[Symbol.toStringTag]' must be of type '"Symbol"', but here has type 'string'.
Error at /Volumes/Projects/lab/ng2-i18n/node_modules/@types/core-js/index.d.ts:457:5: All declarations of '[Symbol.toStringTag]' must have identical modifiers.
Error at /Volumes/Projects/lab/ng2-i18n/node_modules/@types/core-js/index.d.ts:464:5: All declarations of 'prototype' must have identical modifiers.
Error at /Volumes/Projects/lab/ng2-i18n/node_modules/@types/core-js/index.d.ts:492:5: All declarations of 'hasInstance' must have identical modifiers.
Error at /Volumes/Projects/lab/ng2-i18n/node_modules/@types/core-js/index.d.ts:498:5: All declarations of 'isConcatSpreadable' must have identical modifiers.
Error at /Volumes/Projects/lab/ng2-i18n/node_modules/@types/core-js/index.d.ts:504:5: All declarations of 'iterator' must have identical modifiers.
Error at /Volumes/Projects/lab/ng2-i18n/node_modules/@types/core-js/index.d.ts:510:5: All declarations of 'match' must have identical modifiers.
Error at /Volumes/Projects/lab/ng2-i18n/node_modules/@types/core-js/index.d.ts:516:5: All declarations of 'replace' must have identical modifiers.
Error at /Volumes/Projects/lab/ng2-i18n/node_modules/@types/core-js/index.d.ts:522:5: All declarations of 'search' must have identical modifiers.
Error at /Volumes/Projects/lab/ng2-i18n/node_modules/@types/core-js/index.d.ts:528:5: All declarations of 'species' must have identical modifiers.
Error at /Volumes/Projects/lab/ng2-i18n/node_modules/@types/core-js/index.d.ts:534:5: All declarations of 'split' must have identical modifiers.
Error at /Volumes/Projects/lab/ng2-i18n/node_modules/@types/core-js/index.d.ts:540:5: All declarations of 'toPrimitive' must have identical modifiers.
Error at /Volumes/Projects/lab/ng2-i18n/node_modules/@types/core-js/index.d.ts:546:5: All declarations of 'toStringTag' must have identical modifiers.
Error at /Volumes/Projects/lab/ng2-i18n/node_modules/@types/core-js/index.d.ts:552:5: All declarations of 'unscopables' must have identical modifiers.
Error at /Volumes/Projects/lab/ng2-i18n/node_modules/@types/core-js/index.d.ts:609:5: Subsequent variable declarations must have the same type.  Variable '[Symbol.toStringTag]' must be of type '"Math"', but here has type 'string'.
Error at /Volumes/Projects/lab/ng2-i18n/node_modules/@types/core-js/index.d.ts:609:5: All declarations of '[Symbol.toStringTag]' must have identical modifiers.
Error at /Volumes/Projects/lab/ng2-i18n/node_modules/@types/core-js/index.d.ts:613:5: Subsequent variable declarations must have the same type.  Variable '[Symbol.toStringTag]' must be of type '"JSON"', but here has type 'string'.
Error at /Volumes/Projects/lab/ng2-i18n/node_modules/@types/core-js/index.d.ts:613:5: All declarations of '[Symbol.toStringTag]' must have identical modifiers.
Error at /Volumes/Projects/lab/ng2-i18n/node_modules/@types/core-js/index.d.ts:628:5: All declarations of 'size' must have identical modifiers.
Error at /Volumes/Projects/lab/ng2-i18n/node_modules/@types/core-js/index.d.ts:634:5: All declarations of 'prototype' must have identical modifiers.
Error at /Volumes/Projects/lab/ng2-i18n/node_modules/@types/core-js/index.d.ts:645:5: All declarations of 'size' must have identical modifiers.
Error at /Volumes/Projects/lab/ng2-i18n/node_modules/@types/core-js/index.d.ts:651:5: All declarations of 'prototype' must have identical modifiers.
Error at /Volumes/Projects/lab/ng2-i18n/node_modules/@types/core-js/index.d.ts:666:5: All declarations of 'prototype' must have identical modifiers.
Error at /Volumes/Projects/lab/ng2-i18n/node_modules/@types/core-js/index.d.ts:680:5: All declarations of 'prototype' must have identical modifiers.
Error at /Volumes/Projects/lab/ng2-i18n/node_modules/@types/core-js/index.d.ts:692:5: All declarations of 'value' must have identical modifiers.
Error at /Volumes/Projects/lab/ng2-i18n/node_modules/@types/core-js/index.d.ts:804:5: All declarations of 'prototype' must have identical modifiers.
    at check (/Volumes/Projects/lab/ng2-i18n/node_modules/@angular/tsc-wrapped/src/tsc.js:31:15)
    at Tsc.typeCheck (/Volumes/Projects/lab/ng2-i18n/node_modules/@angular/tsc-wrapped/src/tsc.js:86:9)
    at /Volumes/Projects/lab/ng2-i18n/node_modules/@angular/tsc-wrapped/src/main.js:33:23
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Module.runMain (module.js:577:11)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3
Extraction failed
```

Interestingly I also get very similar errors when running the same command on my angular2-seed project

Any ideas what's going on here?

**Comment by klaascuvelier** [comment]
I think this is caused by copying the `tsconfig` config file.
I am not completely sure but I remember looking on Google for these issues and the `duplicate identifier` pointed to 2 `tsconfig` files being used.
If you remove one I think you should be fine.

**Comment by danielcrisp** [comment]
I fixed it with some tweaks to the `tsconfig.json`, see the PR. I was able to keep the e2e tsconfig.json

**Comment by klaascuvelier** [comment]
thanks man.
